version: '3.8'

services:
  prediction_api:
    build: 
      context: ./services/prediction
      dockerfile: ./services/prediction/Dockerfile
    container_name: prediction_service
    ports:
      - "8000:8000"
    volumes:
      - ./services/prediction/api.py:/app/api.py

  explanation_api:
    build: 
      context: ./services/explanation
      dockerfile: ./services/explanation/Dockerfile
    container_name: explanation_service
    ports:
      - "8001:8000"
    volumes:
       - ./services/explanation/api.py:/app/api.py
    env_file:
       - ./.env